name: Publish package
on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - ".github/workflows/main.yaml"
      - "package.json"

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: npm install
      - name: authenticate
        run: echo '//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}' > ~/.npmrc
      - name: lint
        run: npm run lint
      - name: build
        run: npx tsc
      - name: prepare
        run: cp LICENSE README.md package.json src/default.tsconfig.json dist
      - name: publish
        run: npm publish --access public
        working-directory: dist
